// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type Message struct {
	ID            int64          `json:"id"`
	SessionID     int64          `json:"session_id"`
	Exchange      string         `json:"exchange"`
	RoutingKey    string         `json:"routing_key"`
	Body          []byte         `json:"body"`
	ContentType   sql.NullString `json:"content_type"`
	Headers       sql.NullString `json:"headers"`
	Timestamp     sql.NullTime   `json:"timestamp"`
	ConsumedAt    time.Time      `json:"consumed_at"`
	ProtoType     sql.NullString `json:"proto_type"`
	CorrelationID sql.NullString `json:"correlation_id"`
	ReplyTo       sql.NullString `json:"reply_to"`
	MessageID     sql.NullString `json:"message_id"`
	AppID         sql.NullString `json:"app_id"`
}

type MessagesFt struct {
	BodyText   string `json:"body_text"`
	RoutingKey string `json:"routing_key"`
}

type Session struct {
	ID         int64        `json:"id"`
	StartedAt  time.Time    `json:"started_at"`
	EndedAt    sql.NullTime `json:"ended_at"`
	Exchange   string       `json:"exchange"`
	RoutingKey string       `json:"routing_key"`
	QueueName  string       `json:"queue_name"`
	AmqpUrl    string       `json:"amqp_url"`
}
