// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
	"database/sql"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (exchange, routing_key, queue_name, amqp_url)
VALUES (?, ?, ?, ?)
RETURNING id
`

type CreateSessionParams struct {
	Exchange   string `json:"exchange"`
	RoutingKey string `json:"routing_key"`
	QueueName  string `json:"queue_name"`
	AmqpUrl    string `json:"amqp_url"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createSession,
		arg.Exchange,
		arg.RoutingKey,
		arg.QueueName,
		arg.AmqpUrl,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const endSession = `-- name: EndSession :exec
UPDATE sessions SET ended_at = CURRENT_TIMESTAMP WHERE id = ?
`

func (q *Queries) EndSession(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, endSession, id)
	return err
}

const getMessage = `-- name: GetMessage :one
SELECT id, session_id, exchange, routing_key, body, content_type,
       headers, timestamp, consumed_at, proto_type, correlation_id,
       reply_to, message_id, app_id
FROM messages
WHERE id = ?
`

func (q *Queries) GetMessage(ctx context.Context, id int64) (Message, error) {
	row := q.db.QueryRowContext(ctx, getMessage, id)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Exchange,
		&i.RoutingKey,
		&i.Body,
		&i.ContentType,
		&i.Headers,
		&i.Timestamp,
		&i.ConsumedAt,
		&i.ProtoType,
		&i.CorrelationID,
		&i.ReplyTo,
		&i.MessageID,
		&i.AppID,
	)
	return i, err
}

const insertMessage = `-- name: InsertMessage :one
INSERT INTO messages (
    session_id, exchange, routing_key, body, content_type,
    headers, timestamp, proto_type, correlation_id, reply_to,
    message_id, app_id
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id
`

type InsertMessageParams struct {
	SessionID     int64          `json:"session_id"`
	Exchange      string         `json:"exchange"`
	RoutingKey    string         `json:"routing_key"`
	Body          []byte         `json:"body"`
	ContentType   sql.NullString `json:"content_type"`
	Headers       sql.NullString `json:"headers"`
	Timestamp     sql.NullTime   `json:"timestamp"`
	ProtoType     sql.NullString `json:"proto_type"`
	CorrelationID sql.NullString `json:"correlation_id"`
	ReplyTo       sql.NullString `json:"reply_to"`
	MessageID     sql.NullString `json:"message_id"`
	AppID         sql.NullString `json:"app_id"`
}

func (q *Queries) InsertMessage(ctx context.Context, arg InsertMessageParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertMessage,
		arg.SessionID,
		arg.Exchange,
		arg.RoutingKey,
		arg.Body,
		arg.ContentType,
		arg.Headers,
		arg.Timestamp,
		arg.ProtoType,
		arg.CorrelationID,
		arg.ReplyTo,
		arg.MessageID,
		arg.AppID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listMessagesBySession = `-- name: ListMessagesBySession :many
SELECT id, session_id, exchange, routing_key, body, content_type,
       headers, timestamp, consumed_at, proto_type, correlation_id,
       reply_to, message_id, app_id
FROM messages
WHERE session_id = ?
ORDER BY consumed_at DESC
LIMIT ? OFFSET ?
`

type ListMessagesBySessionParams struct {
	SessionID int64 `json:"session_id"`
	Limit     int64 `json:"limit"`
	Offset    int64 `json:"offset"`
}

func (q *Queries) ListMessagesBySession(ctx context.Context, arg ListMessagesBySessionParams) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, listMessagesBySession, arg.SessionID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Exchange,
			&i.RoutingKey,
			&i.Body,
			&i.ContentType,
			&i.Headers,
			&i.Timestamp,
			&i.ConsumedAt,
			&i.ProtoType,
			&i.CorrelationID,
			&i.ReplyTo,
			&i.MessageID,
			&i.AppID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentSessions = `-- name: ListRecentSessions :many
SELECT id, started_at, ended_at, exchange, routing_key, queue_name, amqp_url
FROM sessions
ORDER BY started_at DESC
LIMIT ?
`

func (q *Queries) ListRecentSessions(ctx context.Context, limit int64) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, listRecentSessions, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.StartedAt,
			&i.EndedAt,
			&i.Exchange,
			&i.RoutingKey,
			&i.QueueName,
			&i.AmqpUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
